PANDAS

In [ ]:
# Importing pandas
import pandas as pd

In [40]:
# Series -> One dimensional arrays that can store various data types. 

h = ('AA', '2012-02-01', 100, 10.2) # converting tuple to series
s = pd.Series(h)

type(s)

pandas.core.series.Series

In [41]:
s

0            AA
1    2012-02-01
2           100
3          10.2
dtype: object

In [43]:
# converting dict to Series
d = {'name': 'IBM', 'date':'2010-09-08','shares':100, 'price':10.2}
ds = pd.Series(d)
# print(d)
print(ds)

name             IBM
date      2010-09-08
shares           100
price           10.2
dtype: object


In [44]:
type(ds)

pandas.core.series.Series

In [45]:
m =  ['Jim', '2001-08-02', 90, 3.2]
m = pd.Series(m, index=['name', 'date', 'amount', 'percentage'])
m

name                 Jim
date          2001-08-02
amount                90
percentage           3.2
dtype: object

In [46]:
m['percentage']

3.2

In [48]:
m[['name', 'percentage', 'amount']]

name          Jim
percentage    3.2
amount         90
dtype: object

In [49]:
# DataFrame -> Two Dimensional arrays (row and colum index) 

data = {
    'name': [ 'Jim', 'Ray', 'Paul'],
    'shares': [ '10', '13', '12'],
    'price': [ '200', '131', '144'],
    'color':  [ 'blue', 'red', 'pink'],
}

In [50]:
type(data)

dict

In [51]:
data

{'name': ['Jim', 'Ray', 'Paul'],
 'shares': ['10', '13', '12'],
 'price': ['200', '131', '144'],
 'color': ['blue', 'red', 'pink']}

In [54]:
df = pd.DataFrame(data=data)
type(df)



pandas.core.frame.DataFrame

In [53]:
df

name shares price color
0   Jim     10   200  blue
1   Ray     13   131   red
2  Paul     12   144  pink

In [55]:
df['size'] = ['big', 'small', 'large'] # adding new column 
df

name shares price color   size
0   Jim     10   200  blue    big
1   Ray     13   131   red  small
2  Paul     12   144  pink  large

In [56]:
df['age'] = 'Nan'
df

name shares price color   size  age
0   Jim     10   200  blue    big  Nan
1   Ray     13   131   red  small  Nan
2  Paul     12   144  pink  large  Nan

In [57]:
df.index = ['one','two', 'three'] # Adding index to the DataFrame 
df

name shares price color   size  age
one     Jim     10   200  blue    big  Nan
two     Ray     13   131   red  small  Nan
three  Paul     12   144  pink  large  Nan

In [58]:
df['shares'] # Extracting a column from the DataFrame

one      10
two      13
three    12
Name: shares, dtype: object

In [60]:
df.loc['one'] # select a single row 

name       Jim
shares      10
price      200
color     blue
size       big
age        Nan
Name: one, dtype: object

In [65]:
df.loc[:, 'shares'] # select all the rows in a column 

one      10
two      13
three    12
Name: shares, dtype: object

In [66]:
df.loc['one',:] # select all the column in a row 

name       Jim
shares      10
price      200
color     blue
size       big
age        Nan
Name: one, dtype: object

In [67]:
del df['age'] # deleting a column 

In [68]:
df

name shares price color   size
one     Jim     10   200  blue    big
two     Ray     13   131   red  small
three  Paul     12   144  pink  large

In [69]:
df.drop('shares', axis = 1) # deleting column 

name price color   size
one     Jim   200  blue    big
two     Ray   131   red  small
three  Paul   144  pink  large

In [70]:
df.drop('two', axis=0) # deleting frow 

name shares price color   size
one     Jim     10   200  blue    big
three  Paul     12   144  pink  large

In [72]:
# Reading files 

casts = pd.read_csv('cast.csv', index_col=None) # Reading the cast.csv file
casts.head(3) # Getting the first five elements of the DataFrame

title  year      name   type        character     n
0       Closet Monster  2015  Buffy #1  actor          Buffy 4  31.0
1      Suuri illusioni  1985    Homo $  actor           Guests  22.0
2  Battle of the Sexes  2017   $hutter  actor  Bobby Riggs Fan  10.0

In [73]:
titles = pd.read_csv('titles.csv', index_col=None) # if err -> encoding= 'utf-8'
titles.tail() #getting the last five elements of the DataFrame

title  year
49995                 Rebel  1970
49996               Suzanne  1996
49997                 Bomba  2013
49998  Aao Jao Ghar Tumhara  1984
49999            Mrs. Munck  1995

In [74]:
len(titles)

50000

Data Operations 

In [75]:
# Data Operations 

t = titles['title'] # row and column selection 
type(t)

pandas.core.series.Series

In [76]:
t.head()

0             The Rising Son
1    The Thousand Plane Raid
2           Crucea de piatra
3                    Country
4                 Gaiking II
Name: title, dtype: object

In [77]:
# filtering data

after85 = titles[titles['year'] > 1985] # movies after 1985
after85.head()

title  year
0    The Rising Son  1990
2  Crucea de piatra  1993
3           Country  2000
4        Gaiking II  2011
5       Medusa (IV)  2015

In [78]:
after85.tail()

title  year
49990         Junebug  2005
49993  Corruption.Gov  2010
49996         Suzanne  1996
49997           Bomba  2013
49999      Mrs. Munck  1995

In [79]:
t = titles
movies90 = t[(t['year'] >= 1990) & (t['year'] < 2000)] # display movies in the year 1990 - 1999
movies90 

title  year
0                   The Rising Son  1990
2                 Crucea de piatra  1993
12        Poka Makorer Ghar Bosoti  1996
19                Maa Durga Shakti  1999
24            Conflict of Interest  1993
...                            ...   ...
49969           Chi mei wang liang  1998
49979  Gagay: Prinsesa ng brownout  1993
49987                I Won't Dance  1992
49996                      Suzanne  1996
49999                   Mrs. Munck  1995

[4803 rows x 2 columns]

In [84]:
# sorting

macbeth = t[t['title'] == 'Macbeth'] # find all movies named as Macbeth
macbeth.head()
# len(macbeth)

title  year
4226   Macbeth  1913
9322   Macbeth  2006
11722  Macbeth  2013
17166  Macbeth  1997
25847  Macbeth  1998

In [85]:
macbeth.sort_index() # default is sorted by index 

title  year
4226   Macbeth  1913
9322   Macbeth  2006
11722  Macbeth  2013
17166  Macbeth  1997
25847  Macbeth  1998

In [86]:
macbeth.sort_values('year') # sorting by year

title  year
4226   Macbeth  1913
17166  Macbeth  1997
25847  Macbeth  1998
9322   Macbeth  2006
11722  Macbeth  2013

In [87]:
casts 

title  year                        name     type  \
0                Closet Monster  2015                    Buffy #1    actor   
1               Suuri illusioni  1985                      Homo $    actor   
2           Battle of the Sexes  2017                     $hutter    actor   
3          Secret in Their Eyes  2015                     $hutter    actor   
4                    Steve Jobs  2015                     $hutter    actor   
...                         ...   ...                         ...      ...   
74996  Mia fora kai ena... moro  2011     Penelope Anastasopoulou  actress   
74997         The Magician King  2004       Tiannah Anastassiades  actress   
74998        Festival of Lights  2010             Zoe Anastassiou  actress   
74999                Toxic Tutu  2016             Zoe Anastassiou  actress   
75000           Fugitive Pieces  2007  Anastassia Anastassopoulou  actress   

                     character     n  
0                      Buffy 4  31.0  
1                       Guests  22.0  
2              Bobby Riggs Fan  10.0  
3              2002 Dodger Fan   NaN  
4      1988 Opera House Patron   NaN  
...                        ...   ...  
74996       Popi voulkanizater  11.0  
74997  Unicycle Race Attendant   NaN  
74998       Guidance Counselor  20.0  
74999        Demon of Toxicity   NaN  
75000             Laundry Girl  25.0  

[75001 rows x 6 columns]

In [91]:
c = casts
c['n'].isnull().head()

0    False
1    False
2    False
3     True
4     True
Name: n, dtype: bool

In [95]:
c[c['n'].isnull()].head()

title  year          name   type                character  \
3    Secret in Their Eyes  2015       $hutter  actor          2002 Dodger Fan   
4              Steve Jobs  2015       $hutter  actor  1988 Opera House Patron   
5  Straight Outta Compton  2015       $hutter  actor              Club Patron   
6  Straight Outta Compton  2015       $hutter  actor                  Dopeman   
7          For Thy Love 2  2009  Bee Moe $lim  actor                   Thug 1   

    n  
3 NaN  
4 NaN  
5 NaN  
6 NaN  
7 NaN

In [96]:
c_fill= c[c['n'].isnull()].fillna('NA') # can also use ffill and bfill
c_fill

title  year                        name     type  \
3        Secret in Their Eyes  2015                     $hutter    actor   
4                  Steve Jobs  2015                     $hutter    actor   
5      Straight Outta Compton  2015                     $hutter    actor   
6      Straight Outta Compton  2015                     $hutter    actor   
7              For Thy Love 2  2009                Bee Moe $lim    actor   
...                       ...   ...                         ...      ...   
74984                    Ovum  2015  Christina Rosas Anastasiou  actress   
74985                  7 avlu  2009         Evmorfia Anastasiou  actress   
74993     I teliki apopliromi  2013         Mara Anastasopoulou  actress   
74997       The Magician King  2004       Tiannah Anastassiades  actress   
74999              Toxic Tutu  2016             Zoe Anastassiou  actress   

                           character   n  
3                    2002 Dodger Fan  NA  
4            1988 Opera House Patron  NA  
5                        Club Patron  NA  
6                            Dopeman  NA  
7                             Thug 1  NA  
...                              ...  ..  
74984  Fertility Clinic Receptionist  NA  
74985                          Eleni  NA  
74993                Marina's friend  NA  
74997        Unicycle Race Attendant  NA  
74999              Demon of Toxicity  NA  

[28966 rows x 6 columns]

In [101]:
# String Operations 

t = titles
t[t['title'] == 'Maa'] # searching for the movie Maa


title  year
38880   Maa  1968

In [103]:
t[t['title'].str.startswith('Maa')].head()

title  year
19     Maa Durga Shakti  1999
334          Maarek hob  2004
3046      Maa Aur Mamta  1970
6304   Maampazhakkaalam  2004
7470  Maa Vaibhav Laxmi  1989

In [104]:
# Count values 

t['year'].value_counts().head() # number of years for each year in the DataFrame

2016    2363
2017    2138
2015    1849
2014    1701
2013    1609
Name: year, dtype: int64

In [105]:
c['type'].value_counts().head() # number of actors or actresses in the Dataframe

actor      50000
actress    25001
Name: type, dtype: int64

In [106]:
# merge 

release = pd.read_csv('release_dates.csv', index_col = None) 
release


title  year      country        date
0       #73, Shaanthi Nivaasa  2007        India  2007-06-15
1                     #Beings  2015      Romania  2015-01-29
2                   #Declimax  2018  Netherlands  2018-01-21
3      #Ewankosau saranghaeyo  2015  Philippines  2015-01-21
4                     #Horror  2015          USA  2015-11-20
...                       ...   ...          ...         ...
49995                 Botched  2007           UK  2008-04-18
49996                 Botched  2007         Peru  2010-01-21
49997    Bote, dyaryo, garapa  1989  Philippines  1989-05-26
49998    Both Barrels Blazing  1945          USA  1945-05-17
49999         Botika sa baryo  1960  Philippines  1960-09-23

[50000 rows x 4 columns]

In [107]:
c_amelia = casts[casts['title'] == 'Amelia']
c_amelia

title  year            name   type    character     n
5767   Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0
23319  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0

In [109]:
release[release['title'] == 'Amelia'].head()

title  year    country        date
20543  Amelia  1966     Mexico  1966-03-10
20544  Amelia  2009     Canada  2009-10-23
20545  Amelia  2009        USA  2009-10-23
20546  Amelia  2009  Australia  2009-11-12
20547  Amelia  2009  Singapore  2009-11-12

In [110]:
c_amelia.merge(release)

title  year            name   type    character     n      country  \
0   Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0       Canada   
1   Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0          USA   
2   Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0    Australia   
3   Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0    Singapore   
4   Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0      Ireland   
5   Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0       Mexico   
6   Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0           UK   
7   Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0        Spain   
8   Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0  Philippines   
9   Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0        Italy   
10  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0       Sweden   
11  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0       Turkey   
12  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0      Belarus   
13  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0   Kazakhstan   
14  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0       Russia   
15  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0       Greece   
16  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0       Poland   
17  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0      Belgium   
18  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0        India   
19  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0  Netherlands   
20  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0       Brazil   
21  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0       France   
22  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0      Germany   
23  Amelia  2009    Aaron Abrams  actor  Slim Gordon   8.0        Japan   
24  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0       Canada   
25  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0          USA   
26  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0    Australia   
27  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0    Singapore   
28  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0      Ireland   
29  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0       Mexico   
30  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0           UK   
31  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0        Spain   
32  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0  Philippines   
33  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0        Italy   
34  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0       Sweden   
35  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0       Turkey   
36  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0      Belarus   
37  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0   Kazakhstan   
38  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0       Russia   
39  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0       Greece   
40  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0       Poland   
41  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0      Belgium   
42  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0        India   
43  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0  Netherlands   
44  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0       Brazil   
45  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0       France   
46  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0      Germany   
47  Amelia  2009  Jeremy Akerman  actor      Sheriff  19.0        Japan   

          date  
0   2009-10-23  
1   2009-10-23  
2   2009-11-12  
3   2009-11-12  
4   2009-11-13  
5   2009-11-13  
6   2009-11-13  
7   2009-11-20  
8   2009-12-02  
9   2009-12-23  
10  2010-01-01  
11  2010-01-08  
12  2010-01-14  
13  2010-01-14  
14  2010-01-14  
15  2010-01-21  
16  2010-02-12  
17  2010-03-03  
18  20

In [111]:
c = casts[casts['name']=='Aaron Abrams' ]
c.head(2)

title  year          name   type       character    n
5765       #FromJennifer  2017  Aaron Abrams  actor  Ralph Sinclair  NaN
5766  388 Arletta Avenue  2011  Aaron Abrams  actor            Alex  4.0

In [112]:
c.merge(casts, on=['title', 'year']).head()


title  year        name_x type_x     character_x  n_x  \
0       #FromJennifer  2017  Aaron Abrams  actor  Ralph Sinclair  NaN   
1       #FromJennifer  2017  Aaron Abrams  actor  Ralph Sinclair  NaN   
2  388 Arletta Avenue  2011  Aaron Abrams  actor            Alex  4.0   
3  388 Arletta Avenue  2011  Aaron Abrams  actor            Alex  4.0   
4              Amelia  2009  Aaron Abrams  actor     Slim Gordon  8.0   

               name_y type_y     character_y  n_y  
0        Aaron Abrams  actor  Ralph Sinclair  NaN  
1  Christian Ackerman  actor           Simon  NaN  
2        Graham Abbey  actor      Officer #2  8.0  
3        Aaron Abrams  actor            Alex  4.0  
4        Aaron Abrams  actor     Slim Gordon  8.0

In [113]:
c_costar = c.merge (casts, on=['title', 'year'])
c_costar = c_costar[c_costar['name_y'] != 'Aaron Abrams']
c_costar.head()

title  year        name_x type_x     character_x   n_x  \
1       #FromJennifer  2017  Aaron Abrams  actor  Ralph Sinclair   NaN   
2  388 Arletta Avenue  2011  Aaron Abrams  actor            Alex   4.0   
5              Amelia  2009  Aaron Abrams  actor     Slim Gordon   8.0   
8      Cinderella Man  2005  Aaron Abrams  actor        1928 Fan  67.0   
9      Cinderella Man  2005  Aaron Abrams  actor        1928 Fan  67.0   

               name_y type_y                character_y   n_y  
1  Christian Ackerman  actor                      Simon   NaN  
2        Graham Abbey  actor                 Officer #2   8.0  
5      Jeremy Akerman  actor                    Sheriff  19.0  
8     Nick Alachiotis  actor             Baer Cornerman  38.0  
9     Nick Alachiotis  actor  Undercard Boxer - Feldman  38.0

NUMPY

In [114]:
import numpy as np

In [117]:
# 1-D array
d = np.array([1,2,3])
type(d)

numpy.ndarray

In [116]:
d

array([1, 2, 3])

In [121]:
# multi-dimensional array
nd = np.array([[1,2,3],
                [3,4,5],
                [10,11,12]])
type(nd)

numpy.ndarray

In [120]:
nd

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [10, 11, 12]])

In [122]:
nd.shape # shape of the array

(3, 3)

In [123]:
nd.dtype # data type

dtype('int32')

In [127]:
n = np.zeros((3,3)) # zero matrix

In [128]:
type(n)

numpy.ndarray

In [131]:
e = np.eye(3) # diagonal matrix 

In [132]:
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [133]:
e2 = e + 2 

In [134]:
e2

array([[3., 2., 2.],
       [2., 3., 2.],
       [2., 2., 3.]])

In [135]:
#  create matrix with all entries as 1 and size as 'e2'
o = np.ones_like(e2)
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [136]:
o.dtype

dtype('float64')

In [137]:
oi = o.astype(np.int32)

In [138]:
oi

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [139]:
oi.dtype

dtype('int32')

In [140]:
# accessing data with boolean indexing
data = np.random.randn(5, 3)
data

array([[ 0.06502746, -0.95837107,  0.10261798],
       [ 0.37715943, -0.03965446,  1.13466867],
       [-0.15299705, -0.54108954, -0.15498265],
       [ 1.44476833, -1.7368494 , -0.89846955],
       [-0.46674314,  0.32288272,  0.11604316]])

In [143]:
name = np.array(['a', 'b', 'c', 'a', 'b'])
name == 'a'

array([ True, False, False,  True, False])

In [148]:
a = np.arange(0, 20, 2)

In [149]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [152]:
a.shape

(10,)

In [156]:
a45 = a.reshape(5, 2) # reshaping the arrary 

In [157]:
a45

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [158]:
b = a45[ [2, 0, 1] ] #  select row 2, 0 and 1 from a45 and store in b
b

array([[ 8, 10],
       [ 0,  2],
       [ 4,  6]])

In [159]:
b.T # Transpose array b

array([[ 8,  0,  4],
       [10,  2,  6]])

In [161]:
b.shape

(3, 2)

In [162]:
# Concatenating 

arr = np.arange(12).reshape(3, 4)
rn = np.random.randn(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [163]:
rn

array([[ 1.58465391, -0.55729381, -1.09070934, -1.45043759],
       [-0.77114476,  0.92395972,  1.88994099, -0.33359479],
       [ 0.97281979, -0.67032123,  0.05129625, -0.77177377]])

In [164]:
np.concatenate([arr, rn]) # merge data of rn below the arr 

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ],
       [ 8.        ,  9.        , 10.        , 11.        ],
       [ 1.58465391, -0.55729381, -1.09070934, -1.45043759],
       [-0.77114476,  0.92395972,  1.88994099, -0.33359479],
       [ 0.97281979, -0.67032123,  0.05129625, -0.77177377]])

In [165]:
np.concatenate([arr, rn], axis = 1)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  1.58465391,
        -0.55729381, -1.09070934, -1.45043759],
       [ 4.        ,  5.        ,  6.        ,  7.        , -0.77114476,
         0.92395972,  1.88994099, -0.33359479],
       [ 8.        ,  9.        , 10.        , 11.        ,  0.97281979,
        -0.67032123,  0.05129625, -0.77177377]])